name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey! Thanks for showing interest in my prtoject. This is something I have created as hobby and I am very thankfulk for you putting in time to make this project better together. Cheers!"
        pr-message: "Thanks for sharing the pull request. I will take a look and will reach out in case of any questions!"
